/**
 * Dynamic URL tokens accepted by funnel node page params (mirrors PHP URLTokens::$aAllTokens).
 * Excludes {customfield-random} from pickers (legacy dlgEditPageOptions did the same).
 */
export const FUNNEL_URL_TOKEN_OPTIONS: readonly string[] = [
  '{hit-id}',
  '{visitor-id}',
  '{session-id}',
  '{hit-timestamp}',
  '{location-continent}',
  '{location-countrycode}',
  '{location-countryname}',
  '{location-region}',
  '{location-city}',
  '{location-timezone}',
  '{device-type}',
  '{device-brand}',
  '{device-model}',
  '{device-os}',
  '{device-osversion}',
  '{device-language}',
  '{device-browser}',
  '{device-browserversion}',
  '{connection-ip}',
  '{connection-isp}',
  '{connection-useragent}',
  '{connection-mobilecarrier}',
  '{connection-type}',
  '{campaign-id}',
  '{campaign-name}',
  '{funnel-id}',
  '{funnel-name}',
  '{node-id}',
  '{node-name}',
  '{page-id}',
  '{page-url}',
  '{unix-timestamp}',
  '{referrer}',
  '{referrer-domain}',
  '{flux-domain}',
  '{flux-fts}',
  '{incomingtraffic-id}',
  '{trafficsource-id}',
  '{trafficsource-name}',
  '{trackingfield-fieldname}',
  '{buffer-fieldname}',
] as const
